---
 - name: Playbook to install ThirdParties
   hosts: devops_cluster
   become: true
   tasks:
    - name: Ansible apt install Package
      apt:
        name: chromium
        state: latest
